version: 2.1
orbs:
    node: circleci/node@4.1.0
jobs:
    install-build:
        docker:
            - image: "cimg/base:stable"
        steps:
            - node/install
            - checkout
            - run:
                name: install-ui
                command: |
                    npm run frontend:install
            - run:
                name: install-server
                command: |
                    npm run backend:install
            - run:
                name: build-ui
                command: |
                    npm run frontend:build
            - run:
                name: build-server
                command: |
                    npm run backend:build
